
const { ButtonInteraction } = require('discord.js');
const { ActionRowBuilder, EmbedBuilder, ButtonBuilder, ModalBuilder, TextInputBuilder, TextInputStyle } = require("discord.js");
const { accessSql, profileData, adminsql, reportsql, sequelize } = require('../../../events/database');
const moment = require('moment');



module.exports = {
    id: 'RCclientnew1-button',

    async execute(interaction) {
        if (!(interaction instanceof ButtonInteraction)) return;

        //Récupérer informations de l'utilisateur de la commande
        let authorId = interaction.user.id;
        let authorName = interaction.user.username;
        let userAvatar = `https://cdn.discordapp.com/avatars/${authorId}/${interaction.user.avatar}.png?size=4096`;
        let serverId = interaction.member.guild.id
        let botId = interaction.applicationId


        try {

            //Checkpoint
            console.log("// Step 1 : Initialization - Executed ✅")

            if (interaction.message.interaction.user.id === authorId) {


                //Checkpoint
                console.log("// Step 2 : Authorization - Executed ✅")


                const passwordAdminDashboard = new ModalBuilder()
                    .setCustomId('adminClientNewModal1')
                    .setTitle('New Client');

                // Add components to modal

                // Create the text input components
                const channel = new TextInputBuilder()
                    .setCustomId('newClientAdminDashboardChangeR1')
                    .setLabel("Community Name")
                    .setPlaceholder("The name of the community")
                    .setStyle(TextInputStyle.Short)
                    .setMaxLength(100)

                // Create the text input components
                const channel2 = new TextInputBuilder()
                    .setCustomId('newClientAdminDashboardChangeR2')
                    .setLabel("Server ID")
                    .setPlaceholder("The community's server ID")
                    .setStyle(TextInputStyle.Short)
                    .setMaxLength(40)

                // Create the text input components
                const channel3 = new TextInputBuilder()
                    .setCustomId('newClientAdminDashboardChangeR3')
                    .setLabel("Access Tier")
                    .setPlaceholder('The level of access')
                    .setStyle(TextInputStyle.Short)
                    .setMaxLength(40)

                    // Create the text input components
                const channel5 = new TextInputBuilder()
                .setCustomId('newClientAdminDashboardChangeR5')
                .setLabel("User Count")
                .setPlaceholder('The user count (i.e 340, unlimited)')
                .setStyle(TextInputStyle.Short)
                .setMaxLength(40)

                // Create the text input components
                const channel4 = new TextInputBuilder()
                    .setCustomId('newClientAdminDashboardChangeR4')
                    .setLabel("Pricing")
                    .setPlaceholder('The subscription price per month')
                    .setStyle(TextInputStyle.Short)
                    .setMaxLength(40)





                // An action row only holds one text input,
                // so you need one action row per text input.
                const firstActionRowSetProfile = new ActionRowBuilder().addComponents(channel);
                const secondActionRowSetProfile = new ActionRowBuilder().addComponents(channel2);
                const thirdActionRowSetProfile = new ActionRowBuilder().addComponents(channel3);
                const fourthActionRowSetProfile = new ActionRowBuilder().addComponents(channel4);
                const fifthActionRowSetProfile = new ActionRowBuilder().addComponents(channel5);


                // Add inputs to the modal
                passwordAdminDashboard.addComponents(firstActionRowSetProfile, secondActionRowSetProfile, thirdActionRowSetProfile, fourthActionRowSetProfile, fifthActionRowSetProfile)

                // Show the modal to the user
                await interaction.showModal(passwordAdminDashboard);



            } else {

                const setfpEmbedNotForYou = new EmbedBuilder().setColor("#060A8F")
                    .setTitle("Bot Access")
                    .setAuthor({ name: authorName, iconURL: userAvatar })
                    .setDescription("This button is not for you. You can only click on buttons generated by your commands. Please try again with your personal data.")
                    .setThumbnail('https://cdn.discordapp.com/attachments/1108757847208099941/1133190291428479016/image.png')
                    .setTimestamp()
                    .setFooter({ text: 'Powered by Rolls Chasers', iconURL: 'https://cdn.discordapp.com/attachments/1108757872315219968/1121978623436521514/rc_logo.png' })

                await interaction.reply({ embeds: [setfpEmbedNotForYou], ephemeral: true });



            }

        } catch (error) {


            console.log("// Error - sent in report ❌")

            //On envoi une notif
            let botId = interaction.applicationId
            const botAdmins = await adminsql.findOne({ where: { botId: botId } })
            const mainServerId = botAdmins.dataValues.mainServerId
            const logChannelId = botAdmins.dataValues.logChannelId
            const guild = interaction.client.guilds.cache.get(mainServerId);
            const channel = guild.channels.cache.get(logChannelId);


            const adminAccessInfos = await accessSql.findOne({ where: { serverId: serverId } })
            let adminRoleId = adminAccessInfos.dataValues.adminRoleId
            let serverName = adminAccessInfos.dataValues.serverName
            const userRoleList = interaction.member._roles
            let userHighestRole = "Member"
            if (userRoleList.includes(adminRoleId)) { userHighestRole = "Team" }
            let reportCommand = "/admin-clientNew1"

            const timeStamp = Date.now();
            const date = new Date(timeStamp);
            const dateLisible = date.toLocaleString();
            const date1 = moment(dateLisible, 'M/D/YYYY, h:mm:ss A');
            const formattedDate = date1.format('Do [of] MMMM YYYY');



            //On enregistre le call
            await reportsql.create({
                botId: botId,
                authorId: "Bot",
                serverName: serverName,
                authorRole: userHighestRole,
                serverId: serverId,
                date: formattedDate,
                reportType: "Bug",
                reportCommand: reportCommand,
                reportDescription: "```" + error.stack + "```",
                reportPriority: "5",
                reportState: "Not treated",
            })



            const updateEmbed = new EmbedBuilder().setColor("#060A8F")
                .setTitle("New Report")
                .setDescription(">>> A new report has just been sent.")
                .setThumbnail('https://cdn.discordapp.com/attachments/1108757847208099941/1133190291428479016/image.png')
                .setAuthor({ name: "Rolls Chasers Analytics", iconURL: "https://cdn.discordapp.com/attachments/1108757847208099941/1133190291428479016/image.png" })
                .setTimestamp()
                .addFields(
                    { name: " ", value: " ", inline: false },
                    { name: "Content:", value: "A new `bug` has been submitted for the `" + reportCommand + "` command by `the bot report division` in `" + serverName + "`. You can use the administrator dashboard to consult it.", inline: false },

                )
                .setFooter({ text: 'Powered by Rolls Chasers', iconURL: 'https://cdn.discordapp.com/attachments/1108757872315219968/1121978623436521514/rc_logo.png' })

            await channel.send({ embeds: [updateEmbed] });



            const errorAnswerUser = new EmbedBuilder().setColor("#060A8F")
                .setTitle("An error occured")
                .setDescription("An error has occurred while executing this command. These errors can occur for a variety of reasons, such as :\n∙ Unexpected traffic\n∙ API maintenance\n∙ Occasional bug\n\nPlease note that a report has already been sent to our team, who will fix the problem as soon as possible. You can still use `/report` to give more details about the error and help our team.")
                .setThumbnail('https://cdn.discordapp.com/attachments/1108757847208099941/1133190291428479016/image.png')
                .setTimestamp()
                .setFooter({ text: 'Powered by Rolls Chasers', iconURL: 'https://cdn.discordapp.com/attachments/1108757872315219968/1121978623436521514/rc_logo.png' })


            await interaction.reply({ embeds: [errorAnswerUser], ephemeral: true });


        }

    },
};




